# Generated by Django 4.0.4 on 2022-05-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_crated',
            new_name='date_created',
        ),
    ]
